# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [2]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/site-packages (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/ace-xeon/Library/Python/3.10/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /Users/ace-xeon/Library/Python/3.10/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: /usr/local/opt/python@3.10/bin/python3.10 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Import here.
import pandas as pd

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [4]:
# Load the Food choices data set.

food_data_set_path = "/Users/ace-xeon/Desktop/fall-2026/CTP/ds-fall-2026/Week-02-Pandas-and-How-to-Make-a-Sick-Project/data/food_coded.csv" 

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [5]:
# Count by hand. (lol kidding)
df_food.shape  # It shows the number of rows and columns in the DataFrame.

(125, 61)

In [6]:
# Try to print or display it nicely.
df_food.head() # Shows the first 5 rows of the dataset.

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

What are the columns and their types in this data set?

In [7]:
# Show the column names and their types.
df_food.dtypes

GPA                  object
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports          object
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight               object
Length: 61, dtype: object

In [8]:
pd.set_option("display.max_rows", 100) 

# Make a table showing column names and data types, 
pd.DataFrame({
    "column": df_food.columns, 
    "dtype": df_food.dtypes.astype(str).values
})

                          column    dtype
0                            GPA   object
1                         Gender    int64
2                      breakfast    int64
3               calories_chicken    int64
4                   calories_day  float64
5                 calories_scone  float64
6                         coffee    int64
7                   comfort_food   object
8           comfort_food_reasons   object
9     comfort_food_reasons_coded  float64
10                          cook  float64
11  comfort_food_reasons_coded.1    int64
12                       cuisine  float64
13                  diet_current   object
14            diet_current_coded    int64
15                         drink  float64
16                eating_changes   object
17          eating_changes_coded    int64
18         eating_changes_coded1    int64
19                    eating_out    int64
20                    employment  float64
21                   ethnic_food    int64
22                      exercise  float64
23              father_education  float64
24             father_profession   object
25                   fav_cuisine   object
26             fav_cuisine_coded    int64
27                      fav_food  float64
28                food_childhood   object
29                         fries    int64
30                     fruit_day    int64
31                   grade_level    int64
32                    greek_food    int64
33               healthy_feeling    int64
34                  healthy_meal   object
35                    ideal_diet   object
36              ideal_diet_coded    int64
37                        income  float64
38                   indian_food    int64
39                  italian_food    int64
40                life_rewarding  float64
41                marital_status  float64
42           meals_dinner_friend   object
43              mother_education  float64
44             mother_profession   object
45             nutritional_check    int64
46                 on_off_campus  float64
47                  parents_cook    int64
48                  pay_meal_out    int64
49                  persian_food  float64
50        self_perception_weight  float64
51                          soup  float64
52                        sports  float64
53                     thai_food    int64
54             tortilla_calories  float64
55               turkey_calories    int64
56                   type_sports   object
57                   veggies_day    int64
58                      vitamins    int64
59               waffle_calories    int64
60                        weight   object

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [9]:
# Let's select only the three columns we needed, 
df_food_col_subset = df_food[
    ["calories_day", "weight", "Gender"]
].copy()

df_food_col_subset.head()  # Show the first 5 rows of the subset DataFrame.

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [10]:
# Is there a second way to remove columns?
# OR,
df_food_col_subset_2 = df_food.loc[
    :, ["calories_day", "weight", "Gender"]
].copy()

df_food_col_subset_2.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [11]:
# 🚀 Extra credit: What about a third way to remove columns?
# Dropping all columns except the three we want.
cols_to_drop = df_food.columns.difference(
    ["calories_day", "weight", "Gender"]
)

df_food_col_subset_3 = df_food.drop(
    columns=cols_to_drop
).copy()

df_food_col_subset_3.head()

   Gender  calories_day                    weight
0       2           NaN                       187
1       1           3.0                       155
2       1           4.0  I'm not answering this.
3       1           3.0             Not sure, 240
4       1           2.0                       190

What about `NaN`s? How many are there?

In [12]:
# Counting the missing values in each column. 
df_food_col_subset.isna().sum()

calories_day    19
weight           2
Gender           0
dtype: int64

In [13]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.
df_food_col_subset.isna().sum().rename(
    "missing_values"
).to_frame()

              missing_values
calories_day              19
weight                     2
Gender                     0

In [14]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.
df_food_col_subset.isna() \
    .sum() \
    .rename("missing_values") \
    .to_frame()

              missing_values
calories_day              19
weight                     2
Gender                     0

We gotta remove those `NaN`s―the entire row.

In [15]:
# Drop ‘em in-place.
df_food_col_subset.dropna(inplace=True)

df_food_col_subset.shape

(104, 3)

In [16]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂
print("Original shape: ", df_food.shape)
print("Subset shape: ", df_food_col_subset.shape)

Original shape:  (125, 61)
Subset shape:  (104, 3)

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [17]:
# Convert weight to numbers; invalid values become NaN.
df_food_col_subset["weight"] = pd.to_numeric(
    df_food_col_subset["weight"],
    errors="coerce"
)

# Remove rows where weight could not be converted.
df_food_col_subset.dropna(
    subset=["weight"],
    inplace=True
)

df_food_col_subset.dtypes

calories_day    float64
weight          float64
Gender            int64
dtype: object

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [18]:
# Savey save!
clean_food_path = "cleaned_food_choices.csv"
df_food_col_subset.to_csv(
    clean_food_path, 
    index=False
)

In [19]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.
with open(clean_food_path, "r", encoding="utf-8") as file: 
    for _ in range(5): 
        print(file.readline().strip())

calories_day,weight,Gender
3.0,155.0,1
2.0,190.0,1
3.0,190.0,1
3.0,180.0,2

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [24]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
salary_data_set_path = '../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv'

df_salary = pd.read_csv(
    salary_data_set_path,
    sep="\t"
)

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [25]:
# Count by hand. I’m dead serious.
df_salary.shape

(28062, 18)

What are the columns and their types?

In [26]:
# Show the column names and their types.
pd.DataFrame({
    "column": df_salary.columns,
    "dtype": df_salary.dtypes.astype(str).values
})

                                               column    dtype
0                                           Timestamp   object
1                                    How old are you?   object
2                       What industry do you work in?   object
3                                           Job title   object
4   If your job title needs additional context, pl...   object
5   What is your annual salary? (You'll indicate t...   object
6   How much additional monetary compensation do y...  float64
7                        Please indicate the currency   object
8     If "Other," please indicate the currency here:    object
9   If your income needs additional context, pleas...   object
10                       What country do you work in?   object
11  If you're in the U.S., what state do you work in?   object
12                          What city do you work in?   object
13  How many years of professional work experience...   object
14  How many years of professional work experience...   object
15  What is your highest level of education comple...   object
16                               What is your gender?   object
17        What is your race? (Choose all that apply.)   object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [27]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
new_columns = [
    "timestamp",
    "age",
    "industry",
    "title",
    "title_context",
    "salary",
    "additional_compensation",
    "currency",
    "other_currency",
    "salary_context",
    "country",
    "state",
    "city",
    "total_yoe",
    "field_yoe",
    "highest_education_completed",
    "gender",
    "race"
]

df_salary.columns = new_columns

df_salary.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [28]:
# List the unique industries and a count of their instances.
df_salary["industry"].value_counts(
    dropna=False
)

industry
Computing or Tech                       4699
Education (Higher Education)            2464
Nonprofits                              2419
Health care                             1896
Government and Public Administration    1889
                                        ...
User Experience Design                     1
Environmental science                      1
Homemaker                                  1
CPG                                        1
Aerospace contracting                      1
Name: count, Length: 1220, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [29]:
# Filtery filter.
tech_industry = "Computing or Tech"

df_salary_tech = df_salary[
    df_salary["industry"] == tech_industry
].copy()

Do a sanity check by counting.

In [30]:
# Sanity check count.
print(df_salary_tech.shape)

df_salary_tech["industry"].value_counts()

(4699, 18)

industry
Computing or Tech    4699
Name: count, dtype: int64

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [31]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_salary_tech = df_salary_tech[
    df_salary_tech["currency"] == "USD"
].copy()

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [32]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_tech["country"].value_counts().head(15)

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [33]:
# Get the five most common country spellings.
top_5_countries = (
    df_salary_tech["country"]
    .value_counts()
    .head(5)
    .index
)

# Change those common U.S. spellings to "US".
df_salary_tech.loc[
    df_salary_tech["country"].isin(top_5_countries),
    "country"
] = "US"

Have a look at the count of each unique country again now.

In [34]:
# Count again.
df_salary_tech["country"].value_counts().head(15)

country
US                           3408
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
United States Of America        2
U.S.                            2
Name: count, dtype: int64

Did you notice anything interesting?

In [35]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.
us_pattern = (
    r"(?i)^\s*"
    r"(u\.?s\.?a?|united states(?: of america)?|america)"
    r"\s*$"
)

mask_us = (
    df_salary_tech["country"]
    .astype(str)
    .str.strip()
    .str.match(us_pattern, na=False)
)

# Standardize matching values to "US".
df_salary_tech.loc[mask_us, "country"] = "US"

In [36]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.
df_salary_tech["country"].value_counts().head(20)

country
US                         3704
U.S.A.                        7
Israel                        5
Canada                        4
United State of America       2
Unite States                  2
UnitedStates                  2
India                         2
Australia                     2
Spain                         2
New Zealand                   2
United Kingdom                2
France                        2
Poland                        2
Brazil                        2
Cuba                          1
Danmark                       1
Uniyed states                 1
Remote (philippines)          1
United Stated                 1
Name: count, dtype: int64

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [38]:
# Clean salary and calculate min, mean, and max by U.S. state.
df_salary_tech["salary"] = pd.to_numeric(
    df_salary_tech["salary"].astype(str).str.replace(r"[$,]", "", regex=True),
    errors="coerce"
)

salary_by_state = (
    df_salary_tech[df_salary_tech["country"] == "US"]
    .groupby("state")["salary"]
    .agg(["min", "mean", "max"])
    .sort_values("mean", ascending=False)
)

salary_by_state

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Florida                          28800  157457.232143  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  155224.893130   875000
Washington                          72  151240.498516   950000
New York                         14000  148077.432277   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135515.673333  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127370.512821   450000
Colorado                         45000  127048.895833   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119268.242604   315000
Georgia                          29120  117893.098765   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114849.542169   920000
Texas                            10700  113296.693694   280000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  106752.793103   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
Massachusetts, New Hampshire    105000  105000.000000   105000
New York, Texas                 105000  105000.000000   105000
North Carolina                   29000  104972.127273   260000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
South Carolina                   40000  102111.111111   205000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   97723.055556   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
New Hampshire                       55   93003.437500   193000
Alabama                          29120   92510.000000   350000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Louisiana                        35360   76596.000000   110000
Alabama, Montana                 72000   72000.000000    72000

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [39]:
# Remove $ and commas, then convert salary to numbers.
df_salary_tech["salary"] = pd.to_numeric(
    df_salary_tech["salary"]
    .astype(str)
    .str.replace(r"[$,]", "", regex=True),
    errors="coerce"
)

Let’s try that again.

In [40]:
# Try it again. Yeah!
us_tech = df_salary_tech[
    df_salary_tech["country"] == "US"
].copy()

# Calculate min, average, and max salary by state.
salary_by_state = (
    us_tech.groupby("state")["salary"]
    .agg(["min", "mean", "max"])
    .sort_values("mean", ascending=False)
)

salary_by_state

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Florida                          28800  157457.232143  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  155224.893130   875000
Washington                          72  151240.498516   950000
New York                         14000  148077.432277   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135515.673333  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127370.512821   450000
Colorado                         45000  127048.895833   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119268.242604   315000
Georgia                          29120  117893.098765   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114849.542169   920000
Texas                            10700  113296.693694   280000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  106752.793103   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
Massachusetts, New Hampshire    105000  105000.000000   105000
New York, Texas                 105000  105000.000000   105000
North Carolina                   29000  104972.127273   260000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
South Carolina                   40000  102111.111111   205000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   97723.055556   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
New Hampshire                       55   93003.437500   193000
Alabama                          29120   92510.000000   350000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Louisiana                        35360   76596.000000   110000
Alabama, Montana                 72000   72000.000000    72000

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [41]:
# Convert timestamp to a date/time type.
df_salary_tech["timestamp"] = pd.to_datetime(
    df_salary_tech["timestamp"],
    errors="coerce"
)

# Keep only responses from 2021 and 2022.
df_salary_tech_2021_2022 = df_salary_tech[
    df_salary_tech["timestamp"].dt.year.isin(
        [2021, 2022]
    )
].copy()

# Calculate salary statistics by state.
salary_by_state_2021_2022 = (
    df_salary_tech_2021_2022[
        df_salary_tech_2021_2022["country"] == "US"
    ]
    .groupby("state")["salary"]
    .agg(["min", "mean", "max"])
    .sort_values("mean", ascending=False)
)

salary_by_state_2021_2022

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  155355.206422   875000
Washington                          72  151389.577381   950000
New York                         14000  148317.540462   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135750.677852  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  129797.410256   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127908.189655   450000
Colorado                         45000  127048.895833   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  120121.754491   315000
Georgia                          29120  118738.493671   250000
Maryland                         51260  117889.566038   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114849.542169   920000
Texas                            10700  113303.936364   280000
Florida                          28800  113047.363636   400000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
South Carolina                   40000  109875.000000   205000
District of Columbia, Virginia  109200  109200.000000   109200
Ohio                             32240  107116.696970   954000
Minnesota                        34000  107063.872093   230000
Utah                             33280  105836.479167   245000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
North Carolina                   29000  104880.128440   260000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Alabama                          29120   97738.181818   350000
Michigan                         36800   97723.055556   235000
Missouri                            80   96433.400000   200000
Montana                          65000   95500.000000   145000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
New Hampshire                       55   93003.437500   193000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Louisiana                        35360   76596.000000   110000
Alabama, Montana                 72000   72000.000000    72000

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

In [42]:
# Keep USD responses from all industries.
df_salary_all = df_salary[
    df_salary["currency"] == "USD"
].copy()

# Find common U.S. country spellings.
us_pattern = (
    r"(?i)^\s*"
    r"(u\.?s\.?a?|united states(?: of america)?|america)"
    r"\s*$"
)

mask_us = (
    df_salary_all["country"]
    .astype(str)
    .str.strip()
    .str.match(us_pattern, na=False)
)

# Standardize the country name.
df_salary_all.loc[
    mask_us,
    "country"
] = "US"


# Convert salary text into numeric values.
df_salary_all["salary"] = pd.to_numeric(
    df_salary_all["salary"]
    .astype(str)
    .str.replace(r"[$,]", "", regex=True),
    errors="coerce"
)


# Calculate salary statistics across all industries.
all_salary_by_state = (
    df_salary_all[
        df_salary_all["country"] == "US"
    ]
    .groupby("state")["salary"]
    .agg(["min", "mean", "max"])
    .sort_values("mean", ascending=False)
)

all_salary_by_state

,min,mean,max
state,,,
"Michigan, Texas, Washington",340000,340000.000000,340000
"Indiana, Ohio",245000,245000.000000,245000
Alaska,27040,235263.571429,10000000
"Colorado, Nevada",190000,190000.000000,190000
"California, Montana",185000,185000.000000,185000
...,...,...,...
"District of Columbia, Washington",35000,35000.000000,35000
"Delaware, Pennsylvania",35000,35000.000000,35000
"Alabama, California",29120,29120.000000,29120
"District of Columbia, Maryland, Pennsylvania, Virginia",27040,27040.000000,27040
"Maryland, New York",14000,14000.000000,14000

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

In [43]:
# Display salary values using dollar formatting.
all_salary_by_state.style.format({
    "min": "${:,.2f}",
    "mean": "${:,.2f}",
    "max": "${:,.2f}"
})

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

In [44]:
# List the 50 valid U.S. state names.
valid_states = {
    "Alabama", "Alaska", "Arizona", "Arkansas",
    "California", "Colorado", "Connecticut",
    "Delaware", "Florida", "Georgia", "Hawaii",
    "Idaho", "Illinois", "Indiana", "Iowa",
    "Kansas", "Kentucky", "Louisiana", "Maine",
    "Maryland", "Massachusetts", "Michigan",
    "Minnesota", "Mississippi", "Missouri",
    "Montana", "Nebraska", "Nevada",
    "New Hampshire", "New Jersey", "New Mexico",
    "New York", "North Carolina", "North Dakota",
    "Ohio", "Oklahoma", "Oregon", "Pennsylvania",
    "Rhode Island", "South Carolina",
    "South Dakota", "Tennessee", "Texas",
    "Utah", "Vermont", "Virginia", "Washington",
    "West Virginia", "Wisconsin", "Wyoming"
}

# Keep only responses with one valid state.
df_salary_single_state = df_salary_all[
    (df_salary_all["country"] == "US")
    & (df_salary_all["state"].isin(valid_states))
].copy()

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)

In [45]:
# Percentiles show how salaries are distributed in each state.
quantiles = [
    0,
    0.05,
    0.25,
    0.50,
    0.75,
    0.95,
    1.00
]

salary_quantiles = (
    df_salary_single_state
    .groupby("state")["salary"]
    .quantile(quantiles)
    .unstack()
)

# Give the percentile columns easier names.
salary_quantiles.columns = [
    "0%",
    "5%",
    "25%",
    "50%",
    "75%",
    "95%",
    "100%"
]

# Add the number of responses for each state.
salary_quantiles["count"] = (
    df_salary_single_state
    .groupby("state")["salary"]
    .count()
)

# Sort states by median salary.
salary_quantiles.sort_values(
    "50%",
    ascending=False
)

,0%,5%,25%,50%,75%,95%,100%,count
state,,,,,,,,
California,0.0,42000.00,72000.0,100796.0,147000.00,220000.0,875000.0,2577
Washington,72.0,40000.00,65000.0,90848.0,135000.00,200650.0,1260000.0,1175
New York,80.0,41000.00,64527.5,90000.0,127000.00,210000.0,3000000.0,2163
Massachusetts,155.0,42000.00,64000.0,86000.0,120000.00,184100.0,1650000.0,1507
Maryland,0.0,40000.00,60000.0,82000.0,110000.00,165000.0,353200.0,559
Connecticut,0.0,33702.50,61250.0,81900.0,100000.00,163500.0,1900000.0,234
Virginia,57.0,37340.00,58750.0,81000.0,115000.00,180000.0,1300000.0,778
Delaware,35000.0,40480.00,57546.5,80145.0,105500.00,163297.0,220000.0,47
Oregon,0.0,36340.00,59125.0,78000.0,110000.00,185000.0,320000.0,618
Colorado,65.0,38786.00,58000.0,76000.0,110000.00,165350.0,630000.0,627
Illinois,0.0,37440.00,56000.0,76000.0,109075.00,171800.0,1100000.0,1203
Texas,0.0,35032.00,55000.0,76000.0,110000.00,175000.0,1200000.0,1251
Minnesota,40.0,39520.00,55000.0,75000.0,100000.00,150000.0,321250.0,713
Georgia,0.0,32000.00,53000.0,75000.0,105000.00,173600.0,860000.0,535
New Jersey,14850.0,35744.00,58000.0,75000.0,104000.00,178080.0,5000044.0,393
North Carolina,4000.0,34473.00,51000.0,73000.0,98000.00,150000.0,560000.0,598
Alaska,27040.0,40000.00,59500.0,72800.0,91000.00,144700.0,10000000.0,63
Utah,18720.0,33538.00,54262.5,72653.5,102000.00,175850.0,576000.0,204
Rhode Island,18000.0,35950.00,51250.0,71500.0,93875.00,134250.0,200000.0,76
Pennsylvania,0.0,33127.50,52000.0,70642.0,100600.00,165300.0,1100000.0,938
Nevada,55.0,33753.10,51500.0,70500.0,95100.00,167250.0,425000.0,92
New Mexico,78.0,33892.00,52000.0,69000.0,107000.00,166800.0,300000.0,98
Michigan,55.0,31985.00,52290.0,68000.0,91000.00,148075.0,500000.0,540
Wisconsin,1.0,34050.00,50000.0,67000.0,90000.00,146800.0,920000.0,463
Florida,150.0,31200.00,47788.0,67000.0,97250.00,162100.0,2600000.0,519
Ohio,36.0,33000.00,50000.0,67000.0,89507.50,149100.0,954000.0,647
Arizona,12000.0,34000.00,50000.0,67000.0,100000.00,155200.0,380000.0,299
Missouri,70.0,30500.00,47755.0,65260.0,94625.00,145000.0,335000.0,336
Indiana,105.0,35000.00,49250.0,65000.0,84835.00,134400.0,925000.0,327
New Hampshire,55.0,30977.60,46000.0,65000.0,88500.00,142868.0,208000.0,117
Nebraska,18000.0,32816.75,44620.5,64500.0,88750.00,138750.0,224000.0,106
Tennessee,20800.0,32965.60,47400.0,63000.0,86000.00,157956.0,657900.0,279
Hawaii,12000.0,31107.00,53250.0,62850.0,75000.00,123100.0,500000.0,30
Iowa,13000.0,30000.00,47840.0,62500.0,87500.00,123087.5,200000.0,178
Louisiana,17000.0,30128.00,46650.0,62250.0,85000.00,150000.0,253300.0,128
Kansas,52.0,33550.00,45000.0,61250.0,81250.00,125000.0,734400.0,152
Vermont,24960.0,33590.00,50250.0,61000.0,82500.00,124500.0,200000.0,66
Alabama,54.0,27500.00,45450.0,60500.0,85000.00,142750.0,350000.0,116
Idaho,38.0,30900.00,45940.0,60500.0,78500.00,130000.0,312000.0,96
South Dakota,29000.0,31470.00,44937.5,60175.0,69728.75,127850.0,150000.0,24
Kentucky,0.0,29000.00,43590.0,60000.0,78000.00,130000.0,208000.0,191
Arkansas,26000.0,30680.00,46000.0,60000.0,85000.00,144600.0,488000.0,69
North Dakota,0.0,27584.00,45000.0,59000.0,75000.00,110500.0,150000.0,35
Maine,22000.0,34511.20,43000.0,58500.0,83000.00,114800.0,173000.0,125
South Carolina,0.0,29146.00,43000.0,56500.0,79000.00,128519.0,250000.0,145
Oklahoma,18000.0,27521.60,43000.0,54000.0,80000.00,142200.0,180000.0,113
Mississippi,25000.0,31080.00,36663.0,53000.0,82000.00,113600.0,130000.0,49
Wyoming,29000.0,31803.20,43250.0,50004.0,71500.00,97200.0,140000.0,23
West Virginia,0.0,27000.00,41000.0,49088.0,71400.00,117516.0,125000.0,41
Montana,19200.0,33557.20,37250.0,48000.0,83500.00,125800.0,172000.0,63